-- 1. job_postings 테이블: 이미 identity가 설정되어 있다면 에러가 나므로,
-- 만약의 경우를 대비해 기존 identity 설정을 드랍하고 새로 설정하거나,
-- 아니면 아래와 같이 '성공할 쿼리'만 남겨줘.

-- id 타입을 bigint로 바꾸는 건 안전해 (이미 바뀌었어도 다시 해도 됨)
ALTER TABLE job_postings ALTER COLUMN id TYPE BIGINT USING id::bigint;

-- 이미 identity column이라는 에러가 났으니, 이 부분은 '제거 후 다시 생성'으로 하면 확실해!
ALTER TABLE job_postings ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE job_postings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. posting_stacks 테이블 (아까 여기서 에러가 났었지?)
ALTER TABLE posting_stacks ALTER COLUMN id TYPE BIGINT USING id::bigint;
ALTER TABLE posting_stacks ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE posting_stacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 외래키 타입 변경
ALTER TABLE posting_stacks ALTER COLUMN job_posting_id TYPE BIGINT USING job_posting_id::bigint;