-- 1. 기존 외래키 제약 조건 잠시 삭제 (에러의 주범!)
ALTER TABLE IF EXISTS posting_stacks DROP CONSTRAINT IF EXISTS fkjrkyig8lt8lqxu58826hm627d;

-- 2. job_postings 테이블 수정
ALTER TABLE IF EXISTS job_postings ALTER COLUMN id TYPE BIGINT USING id::bigint;
ALTER TABLE IF EXISTS job_postings ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE IF EXISTS job_postings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 3. posting_stacks 테이블 수정
ALTER TABLE IF EXISTS posting_stacks ALTER COLUMN id TYPE BIGINT USING id::bigint;
ALTER TABLE IF EXISTS posting_stacks ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE IF EXISTS posting_stacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 4. 외래키 컬럼 타입 변경 (이게 이제 통과될 거야!)
ALTER TABLE IF EXISTS posting_stacks ALTER COLUMN job_posting_id TYPE BIGINT USING job_posting_id::bigint;

-- 5. 외래키 제약 조건 다시 생성
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'posting_stacks'
    ) AND EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'job_postings'
    ) THEN
        ALTER TABLE posting_stacks
            ADD CONSTRAINT fkjrkyig8lt8lqxu58826hm627d
                FOREIGN KEY (job_posting_id) REFERENCES job_postings(id);
    END IF;
END $$;
