CREATE EXTENSION IF NOT EXISTS vector;
-- Minimal schema for the real detail-query path. No unrelated domain DDL.
CREATE TABLE job_postings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(500), active integer NOT NULL, start_date varchar(255),
    end_date varchar(255), vcnt integer NOT NULL, cid varchar(255),
    detail text, job_type integer NOT NULL
);
CREATE TABLE posting_stacks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id bigint REFERENCES job_postings(id), stack_id bigint
);
