version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: portmatch-db2-v2
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
